### PR TITLE
Website reorganization

### PR DESCRIPTION
**Pull request by zhales10**

### CODE REVIEW

**Comment by rileyhales** [comment]
i would probably do `/ncaa/mbb` instead of `/ncaambb` because you could conceivably want to talk about college football or volleyball or something. I probably wouldn't add a landing page for `/ncaa` (e.g. no `/ncaa/index.html`)

**Comment by rileyhales** [comment]
You can also just have `/ncaa`

**Comment by zhales10** [comment]
Yes, /ncaa/mbb is better. Let's do that.

I put /ncaambb thinking I would in the future possibly have /ncaawbb,
/ncaaf, etc. But your way is better.

**Comment by rileyhales** [comment]
Things we should change:

- [ ] Drop custom fonts from stylesheets and delete `/static/fonts`
- [ ] Lazy load images

Optional change: Merge the "Sports" and "Blog" button on the nav bar. Its a matter of preference which you keep. I'd probably keep blog. If you click on blog you can find the whole list of articles like it currently does or you can click one of the drop down menu items and end up on one of the other landing pages. We need to start thinking about making your blog more mobile friendly. Its really targeting desktops right now but the overwhelming majority of your readers will be on phones.  Reducing the number of menu items makes it easier to fit all those buttons on a mobile friendly layout.

**Comment by zhales10** [comment]
is there an easy way to replace /ncaambb with /ncaa/mbb other than going into every individual html file and changing it.

lazy load images meaning load them from a website instead of storing the image in /images? I've been doing that recently but haven't gone back to change that for older stuff yet.

I'm fine with getting rid of custom fonts.

what if rather than combining Sports and Blog I move Contact to the bottom of the page next to Privacy?

**Comment by zhales10** [comment]
nevermind, I looked up lazy loading and its not what I said. though I should do that, too.

**Comment by rileyhales** [comment]
i would personally still combine them but regardless the contact does belong at the bottom.

lazy loading is purely a way to increase performance of pages. In the future it will probably become the default way to load things.

Using the tools in the IDE you can automatically add the keyword to turn on lazy loading to all img tags and redo the urls to `/ncaa/mbb`. I can do that. its really fast.

**Comment by rileyhales** [comment]
Done

**Comment by zhales10** [comment]
Thanks. What do I need to do, then? move contact to the bottom? I might also rename Sports to Predictors since the landing page for each of those is the prediction table.

**Comment by rileyhales** [comment]
Thats another option. Part of the reason we put all the posts under `/blog` is to future proof the links to the posts. So while we're rearranging things, consider if you are ok to commit to a certain naming convention for the url patterns for the other landing pages.

For example Does predictors need to be a Nav bar item? or is that more of a block of content you advertise from the home page? The CouchGM home page is a little naked right now and you could fill it with blocks linking you to specific sections of the site like the predictors. Do you want to move all the directories for nba, nfl, etc under 1 parents directory of leagues or sports or something? should there be a `/predictors` section of the site that can merge the content on the home page from all the individual leagues? Or does that belong on `predictors.couchgm.com`? Consider what the purpose of CouchGM is for the future so you can minimize how often you find yourself wanting to rearrange.

**Comment by rileyhales** [comment]
Yes you can move contact to the bottom. Before you change anything on your computer, make sure you use the "update project" button in the IDE -> do `git pull` first. You can know its up to date if you see the changes i've made show up.

**Comment by zhales10** [comment]
I considered doing /predictors or predictors.couchgm.com, but didn't think a subdomain was worth it. So far the predictors is our biggest piece of content. All of the recent posts relate to them and that's basically our thing at this stage. so what I probably should do is overhaul the home page to add links to the different sport predictors. I'll move them all to the /predictor/league structure. Then at the top we'll just have About and Blog.

**Comment by zhales10** [comment]
Just finished moving contact from the menu to the bottom and removed the Sports menu and instead copied all of the link to the predictor tables into the sidebar of /blog/index because that was easier than redesigning the couchgm home page for now. I'll do that another day. But I think we can wrap up reorganization now.

**Comment by zhales10** [comment]
actually I didn't remove the custom fonts yet. To do that should I just delete the whole fonts section in style.css and then delete every time it references font-family in other places of style.css?

**Comment by rileyhales** [comment]
Fixing the css should probably just be its own PR.

**Comment by rileyhales** [comment]
I ran a code quality analysis in WebStorm. Some other things to know about from now on:
- in several places you have links to other sites that go something like `<a href="ncaa.com">`. You always have to include `https://` at the start of the links. Also, do not include `www.` at the start of links unless the website explicitly requires it. I've fixed all of these.
- your tables in the power rankings pages have `<td><font ...`. It should be `<td style="color: green">`. the `<font>` tag is deprecated which means it will causes problems on some browsers. I wrote some code to find and replace those in all the pages on the site. In the future follow the pattern in the html pages.
- there are some links throughout the site which go to blog posts or images that weren't caught when you were arranging things. i've fixed a couple. There are more.
- when you include images with an `` tag, you should include an `alt` attribute. You can google those.
- every page should have a description for it. see https://moz.com/learn/seo/meta-description. It can be generic and short. this is important for Search Engine Optimization and for passing website quality checks. Like all the blog posts can have the description "a blog post about nba power rankings" or something. You can get more elaborate too but something short and sweet is whats important. 
- when we redo the styling of the site, there are lots of bad practices which this template uses which we can fix.

**Comment by zhales10** [comment]
Awesome, thanks. I knew I should put some sort of alt rage but never did...

Where do I add the descriptions?

I'll look at the links again to make sure they are good.

**Comment by rileyhales** [comment]
the descriptions go in a `<meta>` tag in the `<head>` tag which is at the top of the html. the link to moz.com will explain

The remaining links that need to be fixed:

- blog/2020/11/11 see lines 108, 169
- blog/2021/10/19 see line 51
- blog/2021/03/18 see line 72

**Comment by zhales10** [comment]
done

**Comment by zhales10** [comment]
should I do the squash and merge now?

**Pull request merged**
